### ISSUE TITLE
posso adicionar a versão do nullboard aqui?

### ISSUE THREAD

**Issue by lucasnuic** [backend-br/opensource-br#63]
Oi, estou criando uma versão do nullboard com mais recursos, é quase que uma implementação do zero. e é br. posso adicionar a versão do nullboard aqui? o meu projeto é esse: https://github.com/lucasnuic/board

**Comment by vgeruso** [comment]
Eu acredito que sim, realize a alteração na tabela em um fork e faça o pull request para o pessoal poder avaliar e adicionar o seu projeto.

**Comment by lucasnuic** [comment]
Oi @vgeruso, valeu manooo pela info!

**Comment by lucasnuic** [comment]
pull request aceito! nossa que legal! valeu @vgeruso, @gustavofreze
